### ISSUE TITLE
Upgrade Poetry and dependencies

### ISSUE THREAD

**Issue by ansible-hands-on** [glenjarvis/ansible_tutorial#286]
The poetry and dependencies are very out of date for this project. As it is written now, the dependency resolution runs for hours before interrupted.

Do a fresh `pyproject.toml` and freshly add the dependencies so we can get a modern and, unfortunately, more narrow window of dependencies.

**Comment by glenjarvis** [comment]
Fixed with https://github.com/glenjarvis/ansible-hands-on/pull/287
